### ISSUE TITLE
Async encryption/decryption

### ISSUE THREAD

**Issue by lukechilds** [perry-mitchell/iocane#25]
The encryption happens synchronously which blocks the event loop meaning the browser/node process hangs and can't do anything else until encryption has finished.

It would be much better if encryption/decryption happened asynchronously. Any plans to support this? Would you accept a PR?

**Comment by perry-mitchell** [comment]
Hi @lukechilds - I'm only relatively familiar with the Node crypto API, but as far as I'm aware, there isn't a way to make the crypto operations iocane uses truly async. I'm definitely happy to be proven wrong there, however. What solution did you have in mind?

With regards to the [PBKDF2 password derivation](https://github.com/perry-mitchell/iocane/blob/master/source/components.js#L96), that could definitely be made async, and I'd happy accept a PR tackling that.

**Comment by lukechilds** [comment]
I was actually referring to PBKDF2, I think that's what's eating up all the CPU cycles.

Was there any reason it was explicitly set as the sync method? Any gotchas to look out for if I swap this over to async?

**Comment by perry-mitchell** [comment]
Ah ok, I misunderstood. The key derivation process is definitely the worst of it. No gotchas that I can think of- all the interfaces for it are already async 👍
