### ISSUE TITLE
Why are a random amount of PBKDF2 rounds used?

### ISSUE THREAD

**Issue by lukechilds** [perry-mitchell/iocane#27]
A random number between `derivedKeyIterationsMin` and `derivedKeyIterationsMax` is chosen. Why is this?

https://github.com/perry-mitchell/iocane/blob/91f37af4e6e62dedf51fedc03362c8c601ca2fdb/source/derive.js#L15-L20

Is it so if a user re-uses a password they still have a unique key?

If so, why is this beneficial? If someone successfully brute forced a key they would have generated the source password text in the process. They could regenerate the other keys by running the password through PBKDF2 the required amount of rounds.

**Comment by perry-mitchell** [comment]
To be honest it’s probably something I read somewhere when I was building it. I can’t find anything right now to support the idea of using variable iterations.

I suppose it could be removed to allow for a single value, but it’ll have to remain in the composed string of course.

**Comment by perry-mitchell** [comment]
I do like the idea of the key being different each time, for the same password, but of course it probably doesn’t benefit anything. Perhaps for research is needed here before we change anything, however.

**Comment by lukechilds** [comment]
>I do like the idea of the key being different each time, for the same password, but of course it probably doesn’t benefit anything.

It actually reduces the security.

Imagine I find your old hard drive with five encrypted files. They're all using the same password but each with a different amount of PBKDF2 rounds.

All I need to do is bruteforce the key with the least amount of rounds. Then I'll also have the PBKDF2 source password. So I can just run the password through the required amount of PBKDF2 rounds and then I've got the keys for the other four files.

So you essentially reduce the security of all five files to the one with the least amount of rounds.

**Comment by perry-mitchell** [comment]
Good point.. of course that situation is even less likely than being able to brute force a good password.. but it sounds plausible.

I’m in the process of releasing the next major version, so I’ll consider changing this aspect for the next release.

**Comment by perry-mitchell** [comment]
Don’t forget that the minimum is still 200k rounds, which is still quite high in my opinion. It causes significant decryption delay on some devices, and as this has been designed to be used on desktop, mobile and in browser. So even if this aspect is changed, I’ll most likely just set it to 250k.

Raising it 50k in some few cases isn’t crazy significant.

**Comment by lukechilds** [comment]
Oh yes definitely, 200k-250k is more than adequate for Buttercup no matter which value in the range you randomly get.

**Comment by perry-mitchell** [comment]
Ok.. well I’ll tie this task to the new major release to remove the random aspect from it. Thanks 👍

**Comment by lukechilds** [comment]
Great, no problem.

**Comment by perry-mitchell** [comment]
This will be changed in https://github.com/perry-mitchell/iocane/pull/28/files#diff-9e5dca47c8d151271c3689f95566b60fR6 😊
