### ISSUE TITLE
Consider publishing 1.0.0 RCs to npm

### ISSUE THREAD

**Issue by lukechilds** [perry-mitchell/iocane#29]
Would be great if you could publish the RCs to npm so we can pull them into our app.

You can publish the RCs to npm so they're opt in, only people doing:

```
npm install iocane@1.0.0-rc2
```

will get the RC.

Anyone doing:

```
npm install iocane
```

will still get `0.10.1`.

More info: https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420

**Comment by perry-mitchell** [comment]
Hi Luke -

The RCs are published to npm, but under the ‘next’ flag.. They are pre-release and won’t install automatically:

https://user-images.githubusercontent.com/3869469/38988998-f42ea478-43dd-11e8-984d-4d2057b9b3c9.png

You can install the exact version if you’d like, for now:

npm install iocane@1.0.0-rc2

Once I’ve released I’ll update here of course.

**Comment by lukechilds** [comment]
Thanks!

**Comment by perry-mitchell** [comment]
1.0 released as stable. Thanks for the help @lukechilds!
